
server:
  port: 8083

spring:
  application:
    name: subscription-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/netflix_subscription

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
