
server:
  port: 8082

spring:
  application:
    name: content-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/netflix_content

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
